export const PRICE_DISCOUNT_MULTIPLIER = 0.8;
export const PRICE_PARTIAL_DISCOUNT_MULTIPLIER = 0.9;
export const STOCK_REDUCTION_MULTIPLIER = 0.6;
export const ANIMATION_MIN_DURATION_MULTIPLIER = 0.75;
export const ANIMATION_MAX_DURATION_MULTIPLIER = 1.25;